version: '3.9'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    restart: unless-stopped
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    labels:
      - "traefik.enabled=false"
    volumes:
      - elastic-data:/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 127.0.0.1:9200:9200

volumes:
  elastic-data: